### PR TITLE
fix ClockView reload loop

### LINKED ISSUE #1923: Upcoming auction reloads immediately, indefinitely
For live sales scheduled far in the future, the artwork pages reload in a loop forever. As it turns out, this is because `ClockView` we schedules a reload for when the sale goes live using `setTimeout`, which [fires immediately](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Maximum_delay_value) if the number of milliseconds is greater than a 32-bit signed integer, or effectively more than 24.8 days away.

This may be the same cause as #1351.

### PR DESCRIPTION
**Pull request by acjay**
Fixes #1923, at long last.

Debugging the stubbing of reload and time to work properly was a real headache, and sent me chasing many red herrings. I believe it was importing the view dynamically, so that it would capture the stubbed globals, that finally solved the issues.

### CODE REVIEW

**Comment by acjay** [comment]
Weird build failure, retrying...

File: desktop/apps/artwork/components/clock/view.coffee [hunk 1]
```diff
@@ -5,10 +5,13 @@ template = -> require('./index.jade') arguments...
 
 module.exports = class ClockView extends Backbone.View
   initialize: ({ @label, @timestamp }) ->
-    endAt = moment.utc @timestamp
+    endAt = moment.utc(@timestamp)
 
     if endAt.isAfter()
-      setTimeout (-> location.reload()), endAt.diff moment.utc()
+      reloadMs = Math.min(endAt.diff(moment.utc()), 0x7FFFFFFF)
```
Comment (damassi) [inline desktop/apps/artwork/components/clock/view.coffee]: Just curious, what does `0x7FFFFFFF` represent here?

Comment (acjay) [reply desktop/apps/artwork/components/clock/view.coffee]: The maximum value `setTimeout` will accept before firing immediately. I'll add a comment...
