### PR TITLE
@kanaabe => Article Analytics hooks

### LINKED ISSUE #143: QA on article-related events
Following up on https://github.com/artsy/force-private/issues/5375.
cc: @kanaabe @owendodd @anipetrov 

1) `Article impression [social]` fires when social widget is hidden under "Read more".

screen recording 2016-09-13 at 12 02 pm

2) `Article impression [related article]` doesn't fire for related articles.

image 2016-09-13 at 12 07 10 pm

3) `Article impression [artist follow]` sometimes fires when artist follow button is hidden under "Read more".

screen recording 2016-09-13 at 12 25 pm

4) `Article impression [artist follow]` sometimes fires when link to artist page is on page without actual follow button (and sometimes for wrong artist).

image 2016-09-13 at 12 18 57 pm

5) `Article impression [newsletter signup]` fires when box first scrolls into view, rather than when CTA (input form) is visible.

image 2016-09-13 at 12 32 26 pm

6) `Clicked article impression [related article]` doesn't fire for related articles.

image 2016-09-13 at 12 41 33 pm

7) Throughout, `destination_path` should be shortened to path rather than full URL (i.e., only include what's after 'artsy.net').

-----

Additional notes for superarticles:

1) `Article share` doesn't fire from social widgets at the top of the page.

image 2016-09-13 at 12 35 20 pm

2) `Article impression [table of contents]` doesn't fire at all (unless this is an anomalous case?).

image 2016-09-13 at 12 36 54 pm

### PR DESCRIPTION
**Pull request by eessex**
Closes #143 

Distinguish visible and non-visible links inside read-more.
Add support for related articles component for impressions and clicks.

### CODE REVIEW

File: analytics/article_impressions.js [hunk 1]
```diff
@@ -38,10 +38,34 @@ if(location.pathname.match('/article/') || location.pathname.match('/articles'))
               id: 'magazine_fixed'
             }
           }
+        }else if(classList.contains('article-es-form')){
+          var article = $(this).parent().parent().parent().parent();
```
Comment (kanaabe) [inline analytics/article_impressions.js]: This isn't a very reliable selector! What would happen if we changed the order of parents or even more likely, if we decide to remove some container we don't need? We'll want to find use `parents` or `closest` instead. See https://www.sitepoint.com/jquerys-closest-parents/

File: analytics/article_impressions.js [hunk 2]
```diff
@@ -68,35 +92,65 @@ if(location.pathname.match('/article/') || location.pathname.match('/articles'))
...
+            article_id: articleId,
+            destination_path: null,
+            impression_type: 'article_fixed',
+            context_type: 'toc',
+            id: 'toc:' + articleId
+          }
+
+        // Related Article
+        }else if(classList.contains('article-related-widget')){
+          var related = $(this).children('ul').children().children('a')
```
Comment (kanaabe) [inline analytics/article_impressions.js]: Same here, `find` is probably a better option

File: analytics/article_impressions.js [hunk 3]
```diff
@@ -117,15 +171,21 @@ if(location.pathname.match('/article/') || location.pathname.match('/articles'))
 
   var trackImpressions = function() {
     // Find signups, cta, share buttons, artist follow, toc, and image sets
-    var items = $('.articles-es-cta, .article-social, .article-section-image-set, .article-section-toc, .artist-follow, .article-section-callout');
-
+    var items = $('.articles-es-cta__form, .article-es-form, .article-social, .article-share-fixed-fullscreen, .article-section-image-set, .article-section-toc, .article-sa-sticky-header.visible, .article-sa-related, .artist-follow, .article-section-callout, .article-related-widget');
```
Comment (kanaabe) [inline analytics/article_impressions.js]: Just a style thing, but this could be broken down into multiple lines. Maybe you could define the selector string prior with multilines, and then say `var items = $(selectorString)`

File: analytics/article_impressions.js (hunk 1 above)
Comment (eessex) [inline analytics/article_impressions.js]: Thanks - I hadn't seen the plural parents before, very helpful!

Comment (kanaabe) [inline analytics/article_impressions.js]: Yep! Definitely read the article -- it's an interesting comparison between `parents` and `closest` and does some performance testing to prove that `closest` is the faster choice, but this works too!

File: analytics/articles.js [hunk 4]
```diff
@@ -43,11 +43,20 @@ if(location.pathname.match('/article/')){
...
     analytics.track('Clicked article impression', {
       article_id: articleId,
-      destination_path: $(this)[0].href,
+      destination_path: $(this)[0].href.replace(/^.*\/\/[^\/]+/, ''),
       impression_type: 'article_callout',
       context_type: 'article_fixed'
     });
 
+  }).on('click', '.article-related-widget a', function(){
+    var articleId = $(this).parent().parent().parent().data('id');
```
Comment (kanaabe) [inline analytics/articles.js]: Whoops, missing one more here!

Comment (kanaabe) [inline analytics/articles.js]: Actually with this commit, I would go ahead and use `closest` to optimize for speed

Comment (eessex) [inline analytics/articles.js]: Cool -- just went through and replaced these, also managed to do some rebasing!

**Comment by kanaabe** [comment]
Excellent! Great work.
