### PR TITLE
@sweir27 - Fix generic gene follow button on homepage

### LINKED ISSUE #980: Gravity errors when homepage renders generic gene modules
As a logged-in user on staging (so, no artist follows) the home page renders okay but throws these errors in the console:

image

It appears to be trying to call the `/api/v1/me/follow/artists` endpoint, passing in the `gene_id` as the `artist_id`.

### PR DESCRIPTION
**Pull request by broskoski**
Closes #980

### CODE REVIEW

File: desktop/apps/home/components/follow_button/index.coffee [hunk 1]
```diff
@@ -16,8 +16,10 @@ followableObject =
 module.exports = ({ module, user, $el }) ->
   return unless followableObject[module.key]?
 
-  kind = if module.key is 'related_artists' or 'followed_artist' then 'artist' else 'gene'
-  Model = if module.key is 'related_artists' or 'followed_artist' then Artist else Gene
+  artistRelated = module.key is 'related_artists' or module.key is 'followed_artist'
```
Comment (mzikherman) [inline desktop/apps/home/components/follow_button/index.coffee]: tricksy coffeescript!

**Comment by sweir27** [comment]
Whoa. Thank you!
